def ext_throws():
    raise ValueError('this is the error message')
